version: '2'
services:

 apigateway:
  build: .
  ports:
   - "8080:8080"
  environment:
   SPRING_PROFILES_ACTIVE: uat
   MESSAGES_ENDPOINT: 3.93.76.44
   POSTS_ENDPOINT: 3.212.247.122
   CLIENT_ENDPOINT: 35.173.218.135
   PROVIDER_ENDPOINT: 3.83.41.64
   FAVORITES_ENDPOINT: 54.196.220.119
   RESERVATION_ENDPOINT: 18.212.38.158
