version: '2'
services:

 apigateway:
  build: .
  ports:
   - "8080:8080"
  environment:
   SPRING_PROFILES_ACTIVE: uat
   MESSAGES_ENDPOINT: 3.93.76.44
   POSTS_ENDPOINT: 3.212.247.122
   USER_ENDPOINT: 3.222.8.195   
   RESERVATION_ENDPOINT: 3.229.229.156
   AUTH_ENDPOINT: 18.212.38.158
