server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: Messages
          uri: http://${MESSAGES_ENDPOINT}:8080/
          predicates:
            - Path=/messages/**
        - id: Posts
          uri: http://${POSTS_ENDPOINT}:8080/
          predicates:
            - Path=/posts/**,/comments/**
        - id: User
          uri: http://${USER_ENDPOINT}:8080/
          predicates:
            - Path=/users/**,/favorites/**,/login/**
        - id: Reservation
          uri: http://${RESERVATION_ENDPOINT}:8080/
          predicates:
            - Path=/reservation/**,/payment/**